Exercise retrieval updates
exercism/python-representer pull request #13
Opened 2020-11-10 08:58 UTC by BethanyG

- Added code and some error handling for retrieving the exercise file name from either `config.json` or via the passed-in slug name.
- Changed the SLUG_RE code to accept an underscore as part of a valid slug name

Decided to not change the code to accept more than one exercise file since we don't currently have any mulit-file exercises in either the concept nor practice categories.

2020-11-10 16:45 UTC, cmccandless requested changes

2020-11-10 16:45 UTC, cmccandless commented on representer/__init__.py
> +            return
```suggestion
        if not src.is_file():
            print('No exercise file was found in the input directory.', err)
            return
```

2020-11-10 16:45 UTC, cmccandless commented on representer/utils.py
> +SLUG_RE = re.compile(r"^[a-z]+([-_][a-z]+)*$")
Slugs aren't supposed to contain underscore, and I don't see anything in your other changes that required this change. Can you clarify why this change is necessary?

2020-11-11 16:26 UTC, BethanyG commented on .github/CODEOWNERS
> +* @bethanyg
```suggestion
* @cmccandless @bethanyg
```

2020-11-11 16:28 UTC, BethanyG commented on representer/utils.py
> +SLUG_RE = re.compile(r"^[a-z]+([-_][a-z]+)*$")
There was some ambiguity in concept exercise naming.  That's been resolved, and the new requirement is that all concept exercises be named for their stories and use `kebab case`.  So yes, the underscore should be removed -- thanks for catching that!

2020-11-11 16:28 UTC, BethanyG commented on representer/utils.py
> +SLUG_RE = re.compile(r"^[a-z]+([-_][a-z]+)*$")
```suggestion
SLUG_RE = re.compile(r"^[a-z]+(-[a-z]+)*$")
```

2020-11-11 20:03 UTC, cmccandless approved these changes

2020-11-11 20:03 UTC, merged